better arch detection and option to override

diff --git a/rootfs/etc/services.d/airspy_adsb/run b/rootfs/etc/services.d/airspy_adsb/run
--- a/rootfs/etc/services.d/airspy_adsb/run
+++ b/rootfs/etc/services.d/airspy_adsb/run
@@ -106,26 +106,54 @@ if [[ "${AIRSPY_ADSB_VERBOSE^^}" == "TRUE" ]]; then
     AIRSPY_ADSB_CMD+=("-v")
 fi
 
-# Determine which architecture binary is supported, else fail.
-if /usr/local/bin/airspy_adsb.aarch64 -h > /dev/null 2>&1; then
-    AIRSPY_ADSB_BIN="/usr/local/bin/airspy_adsb.aarch64"
-    echo "Using aarch64 binary" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
-elif /usr/local/bin/airspy_adsb.armhf -h > /dev/null 2>&1; then
-    AIRSPY_ADSB_BIN="/usr/local/bin/airspy_adsb.armhf"
-    echo "Using armhf binary" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
-elif /usr/local/bin/airspy_adsb.i386 -h > /dev/null 2>&1; then
-    AIRSPY_ADSB_BIN="/usr/local/bin/airspy_adsb.i386"
-    echo "Using i386 binary" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
-elif /usr/local/bin/airspy_adsb.x86_64 -h > /dev/null 2>&1; then
-    AIRSPY_ADSB_BIN="/usr/local/bin/airspy_adsb.x86_64"
-    echo "Using x86_64 binary" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
-else
-    >&2 echo "ERROR: Unsupported architecture: $(uname -m)!" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
-    sleep infinity 
+# Handle architecture
+if [[ -z "$AIRSPY_ADSB_ARCH" ]]; then
+
+    echo "[airspy_adsb] Autodetecting architecture"
+
+    # Determine which architecture binary is supported, else fail.
+    if /usr/local/bin/airspy_adsb.arm64 -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="arm64"
+
+    elif /usr/local/bin/airspy_adsb.armv7 -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="armv7"
+
+    elif /usr/local/bin/airspy_adsb.arm -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="arm"
+
+    elif /usr/local/bin/airspy_adsb.nehalem -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="nehalem"
+
+    elif /usr/local/bin/airspy_adsb.x86_64 -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="x86_64"
+
+    elif /usr/local/bin/airspy_adsb.i386 -h > /dev/null 2>&1; then
+        AIRSPY_ADSB_ARCH="i386"
+        
+    else
+        >&2 echo "[airspy_adsb] ERROR: Unsupported architecture: $(uname -m)!"
+        sleep infinity 
+    fi
+fi
+
+# Specify binary path
+AIRSPY_ADSB_BIN="/usr/local/bin/airspy_adsb.${AIRSPY_ADSB_ARCH}"
+
+# Ensure binary exists
+if [[ ! -x "$AIRSPY_ADSB_BIN" ]]; then
+    >&2 echo "[airspy_adsb] ERROR: Executable binary not found for architecture: $AIRSPY_ADSB_ARCH!"
+        sleep infinity 
+fi
+
+# Ensure binary runnable
+if ! "$AIRSPY_ADSB_BIN" -h > /dev/null 2>&1; then
+    >&2 echo "[airspy_adsb] ERROR: Executable $AIRSPY_ADSB_ARCH binary not supported on $(uname -m) architecture!"
+        sleep infinity 
 fi
 
 # Execute binary with arguments prepared above
-echo "Running: airspy_adsb" "${AIRSPY_ADSB_CMD[@]}" | stdbuf -oL awk '{print "[airspy_adsb] " $0}'
+echo "[airspy_adsb] Running $AIRSPY_ADSB_ARCH binary on $(uname -m) architecture."
+echo "[airspy_adsb] Running: airspy_adsb" "${AIRSPY_ADSB_CMD[@]}"
 
 #shellcheck disable=SC2016
 "${AIRSPY_ADSB_BIN}" "${AIRSPY_ADSB_CMD[@]}" \
